### ISSUE TITLE
Authenticate error

### ISSUE THREAD

**Issue by caifazhou** [navisens/Android-SDK#1]
Dear Navisens Team,
I am trying to use Navisens Android SDK using a developer key. But I got an authentication problem.

// Error message
Error: authentication failed Error: Didn't authenticate for too long. Please reauthenticate or contact Navisens.

I applied the API key less than 2 weeks ago and I use it first time today. Do you have any clue about this error? Thanks.

**Comment by caifazhou** [comment]
I've confirmed the Internet access. But I changed to a new phone. Is that possible just because the new cellphone?

**Comment by lucasnavisens** [comment]
Hi,

Sorry for the late reply.
How is everything going ?

You had internet access on the new phone when you tried authenticating ?

Cheers.

**Comment by ODINA101** [comment]
same here :( did you fix it?

**Comment by jamesgrantham** [comment]
Hi ODINA101,
Are you using the latest version 2.0.1 of our SDK? Older versions 1.9.5 or early may experience authentication issues even with a stable internet connection, however this should be resolves in the latest SDK.

If this doesn't address your issue could you provide a little more information on what you are experiencing? Some things that could be helpful for troubleshooting...

Device model
Android version
Whether your app was first started on cellular or wifi?

If you like you can also send your developer key to support@navisens.com and we can take a look at whether we saw a successful authentication on our servers.
Cheers

**Comment by ODINA101** [comment]
@jamesgrantham thanks for fast reply i am using 1.9.2 version and you answer is solution for this,
but when i trying to use ` implementation "com.navisens:motiondnaapi:+"` or 
`implementation group: "com.navisens", name: "motiondnaapi", version: "2.0.1", changing: true` 
gives me build errors

**Comment by jamesgrantham** [comment]
That is probably due to our SDK API changing quite substantially since the 1.9.X to 2.0.X versions. 
MotionDnaApplication is now MotionDnaSDK  to match with its iOS counterpart.

This link should have all the new API calls. I believe they should be much simpler to understand than what we had before.
https://github.com/navisens/NaviDocs/blob/master/API.Android.md

Let me know if you have any more questions

**Comment by ODINA101** [comment]
i change MotionDnaApplication and giving other symbol errors i cloned their project on github
[https://github.com/navisens/react-native-helloworld/blob/master/android/app/src/main/java/com/reactnativehelloagainworld/MotionDnaSynchronizedApplication.java](url)

they have used MotionDnaApplication :/

**Comment by jamesgrantham** [comment]
Ah sorry I did not realize that you were using the React Demo. That project is still in the process of being updated for 2.0.0. In the meantime. 1.9.6 should work or you can check out any of our other native demos which are alread updated to use the new API.
https://github.com/navisens/android-app-helloworld
https://github.com/navisens/android-app-map-manual-location
