### ISSUE TITLE
[Android-SDK ] No codes after 1.2.1 snapshot 

### ISSUE THREAD

**Issue by jax79sg** [navisens/Android-SDK#2]
Hi, I noted only a license file and a readme.md in your Android-SDK repository after version 1.2.1 snapshot. What happened to the example codes? 
Do you also have a javadoc explaining your SDK?

Thanks.

**Comment by lucasnavisens** [comment]
Hi you can visit our NaviDocs on how to use our plugins:
https://github.com/navisens/NaviDocs/blob/master/BEER.Android.md
If you are using native, you can follow:
https://github.com/navisens/NaviDocs/blob/master/API.Android.md

Which explains how to setup the native SDK.
We will be uploading a native example soon.

Cheers!

**Comment by jax79sg** [comment]
Hi, thanks for the update.
