### ISSUE TITLE
Issue with building with multiple floors

### ISSUE THREAD

**Issue by Shahroz16** [navisens/Android-SDK#3]
Thank you for a very helpful SDK. 

I have tested it out thoroughly, it works really smooth on the single floor but as soon as you go on a different floor, it loses the track of direction.

Any ideas?

**Comment by jamesgrantham** [comment]
Hi Sharon would you mind providing additional info? Are you using one of our sample GitHub projects to test or have you integrated our SDK into your own test app?

Keep in mind that background modes for location must be enabled in order for us to continue estimating when the screen is off or the app has been backgrounded.

What initialization method calls are you using when starting the SDK?

**Comment by Shahroz16** [comment]
I am using the Android demo from the Play store. I can try the sample Github project as well
