### ISSUE TITLE
Forbidden numeric value: NaN

### ISSUE THREAD

**Issue by DmitryAverin** [navisens/Android-SDK#4]
Hello! I use the  latest Navisens Sdk (1.8.13) In my app navisens can be paused and returned few times. And I note that after few iterations (count can be different time by time) of this lifecycle navisens make too many exceptions. StackTrace is next:
`W/System.err:     org.json.JSONException: Forbidden numeric value: NaN`
`W/System.err:     at org.json.JSON.checkDouble(JSON.java:25)`
`W/System.err:     at org.json.JSONObject.put(JSONObject.java:265)`
`W/System.err:     at org.json.JSONTokener.readObject(JSONTokener.java:384)`
`W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:100)`
`W/System.err:     at org.json.JSONTokener.readObject(JSONTokener.java:384)`
`W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:100)`
`W/System.err:     at org.json.JSONTokener.readObject(JSONTokener.java:384)`
`W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:100)`
`W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:159)`
`W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)`
`W/System.err:     at com.navisens.motiondnaapi.MotionDnaJNI.receiveResultData(Unknown Source:2)`

So in this case I can not get user position.
Phone which used for testing sdk: Samsung Galaxy A3 (2017) Android version 8.0
Before updating to 1.8.13 I used version 1.7.1 and all working fine

**Comment by jamesgrantham** [comment]
Hello Dmitrym
Does this error occur every time you run our SDK? Or is the problem intermittent?

**Comment by DmitryAverin** [comment]
Yes, It is occur every time. It is replicate for me with next steps:
1) create implementation MotionDnaInterface for initializing navisens
2) in receiveMotionDna method I implement my own business logic which use method setLocalHeading and use own property MotionDna.location.magneticHeading (I use this methods only once on first calling receiveMotionDna)
3) call MotionDnaApplicaton.pause()
4) when I need call MotionDnaApplication.resume() I call resetLocalEstimation() , setHeadingMagInDegrees() and setCallbackUpdateRateInMs()
5) I retry steps 3 and 4 for three times and my problem will occur on third iteration

**Comment by jamesgrantham** [comment]
Thanks for the detailed steps! We will see if we can reproduce on our end and if we can I'll let you know when we have a solution to the bug.

**Comment by jamesgrantham** [comment]
Hi Dmitry,
We were unable to reproduce here. Would you be able to send the exact SDK calls and the order you use to initialize the SDK, to pause it, and to resume? knowing this might help us narrow it down.
