### ISSUE TITLE
Is there support for requesting MotionDna without a Callback?

### ISSUE THREAD

**Issue by jkhall** [navisens/Android-SDK#6]
Hi. I was just wondering if there's anything available like motionDnaSdk.GetDna(), or something like that where you can just ask for new motionDna. We have a potential use case where we would like to poll the sdk ourselves. I do realize that the callback delay is configurable, but I just thought I'd ask.

Thanks!

**Comment by jamesgrantham** [comment]
Hi there, we currently do not have any support for directly requesting the most recent estimation object. My recommendation would be to implement a MotionDnaSDKListener object that has a MotionDna object as a member variable that is updated by the callback and then implement a getter for it in there
